# generated by configure / remove this line to disable regeneration
prefix="/home/huangl/workspace/RfCgraTrans/build/pluto"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/huangl/workspace/RfCgraTrans/pluto/polylib/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/huangl/workspace/RfCgraTrans/pluto/polylib/./include"
package="polylib64"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "polylib64"
;; --help) pkg-config --help ; echo Buildscript Of "polylib64 Library"
;; --modversion|--version) echo "5.22.5b"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lpolylib64"
       :
;; --cflags) echo -I${includedir} ""
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
