# generated by configure / remove this line to disable regeneration
prefix="/home/huangl/workspace/RfCgraTrans/build/pluto"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/huangl/workspace/RfCgraTrans/pluto/cloog-isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/huangl/workspace/RfCgraTrans/pluto/cloog-isl/./include"
package="cloog-isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "cloog-isl"
;; --help) pkg-config --help ; echo Buildscript Of "cloog-isl Library"
;; --modversion|--version) echo "0.20.0"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "-L/lib" "-lcloog-isl -lgmp"
       :
;; --cflags) echo -I${includedir} "-DISL_USING_GMP_VAL=1"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
