#include <vector>
#include <iostream>
#include <memory.h>
#include <gflags/gflags.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <fstream>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <ctime>
#include <sys/time.h>
#include <glog/logging.h>
#include <set>
#include <map>
#include <assert.h>
#include <algorithm>
#include <sstream> 
#include <stack>
#define INF 0x3f3f3f3f